### ISSUE TITLE
peaks 'n phase reporting issue?

### ISSUE THREAD

**Issue by bturkus** [pugetsoundandvision/audioqc#2]
Hi Andrew,

Playing around with audioqc I've been encountering some errors I'd love to perspective on. When I run audioqc with the `-d` flag, it combs through all the files and gives a nice CSV report, but when running the script with no flag, or with the `-a` flag, it seems to quit after FFmpeg processes the first file. Consistently, I've been seeing the following:

```
./audioqc:216:in `find_peaks_n_phase': undefined method `sum' for #<Array:0x00007fcbdc8929c0> (NoMethodError)
	from ./audioqc:283:in `block in <main>'
	from ./audioqc:266:in `each'
	from ./audioqc:266:in `<main>'
```
Thanks!!

Ben

**Comment by privatezero** [comment]
Hey Ben,

I'm guessing you are on a mac, right? I _think_ the problem might be that the way I am summing the values of that array might not work in the older version of Ruby that macs have. I've gotten into trouble with that before, so seems likely it might be the same kind of problem. I'll take a look at making that command compatible with older Ruby! (And hopefully that is actually the issue)

Thanks for testing!!

**Comment by bturkus** [comment]
I can also try updating Ruby on my end! Will do so and report back. Thank you thank you

**Comment by privatezero** [comment]
Out of curiosity, what version do you get when you go into a Ruby terminal window (type `irb` in the normal terminal) and then run `puts RUBY_VERSION`

I think I might throw in a system check to change the command if someone is running an older version of Ruby, as it looks like the `sum` command is _slightly_ faster than alternatives when it is available.

**Comment by bturkus** [comment]
Weird. It was 2.7.2, but I upgraded to 3.0.0 (confirmed with a `puts RUBY_VERSION`), and I'm still getting the peaks 'n phase error.

**Comment by privatezero** [comment]
lol thanks for trying (and scratch that theory!) I'll poke around some more!

**Comment by privatezero** [comment]
Ok, one last theory to test clinging to version issues - I have a couple branches that I think _might_ fix it for you to test:

[ben-test-1](https://github.com/pugetsoundandvision/audioqc/tree/ben-test-1): this changes the ruby shebang to be more versatile I think
[ben-test-2](https://github.com/pugetsoundandvision/audioqc/tree/ben-test-2): this adds in a conditional for a different command

Let me know if either of those seem to help!

**Comment by bturkus** [comment]
both work, thanks! I'm noticing a small difference in the CSV report (ascending v. descending), but all good. Really appreciate this entire project, and I'll be sure to keep testing and working this into our way of doing things.

**Comment by privatezero** [comment]
Rad - I'll merge 'em both! That will teach me for being lazy with the shebangs - I guess I had basically hard coded the script to ignore your updated version of Ruby and to use whatever old version was still floating in around in there :-P

Thanks so much for the testing - definitely let me know any ways it could be made more useful!

Relatedly - I had started a draft script in the same directory to basically create a PDF of `showspectrumpic` outputs. Y'all have been using `showspectrumpic` a lot in your qc process - right? Any tips/thoughts on things that worked with integrating it into a mass qc workflow?

**Comment by bturkus** [comment]
I saw that (the showspectrum)! We've never figured out exactly how to implement into our mass qc, but we'll give this PDF a try for sure

**Comment by privatezero** [comment]
Thanks! It is VERY drafty at this point (I haven't listed dependencies either) but I was just thinking of how to get something that myself (or another QC person) could quickly tab through.Not sure if it'll help anything though!
